spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:~/testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  profiles:
    include: security